services:
  api:
    build: ./apps/api
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    ports: ["8000:8000"]
  web:
    build: ./apps/web
    environment:
      NEXT_PUBLIC_API_BASE: "http://localhost:8000"
    ports: ["3000:3000"]
    depends_on: [api]
