[project]
name = "patentalchemy-api"
version = "0.2.0"
requires-python = ">=3.11"
dependencies = [
  "fastapi>=0.112.0",
  "uvicorn>=0.30.0",
  "pydantic>=2.7.0",
  "requests>=2.32.3",
  "beautifulsoup4>=4.12.3"
]

[tool.uvicorn]
reload = true
host = "0.0.0.0"
port = 8000
